'use strict';

/**
 * Bengaluru City Police contact directory (Law & Order stations, Traffic PI, Senior officers).
 * Source: City_Police_Contact_info CSV datasets.
 */

module.exports = {
  stations: [
    {
      name: "Ashoknagar",
      division: "Central",
      subdivision: "Cubbonpark",
      phone: "080 22942076",
      email: "anagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Cubbon Park",
      division: "Central",
      subdivision: "Cubbonpark",
      phone: "080 22942087",
      email: "cparkbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Vidhana Soudha",
      division: "Central",
      subdivision: "Cubbonpark",
      phone: "080 22942086",
      email: "vsoudhabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Viveknagar",
      division: "Central",
      subdivision: "Cubbonpark",
      phone: "080 22942080",
      email: "vknagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Halasoor Gate",
      division: "Central",
      subdivision: "Halasoor Gate",
      phone: "080 22942075",
      email: "hgatebcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "S .R. Nagar",
      division: "Central",
      subdivision: "Halasoor Gate",
      phone: "080 22942078",
      email: "srnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Wilson Garden",
      division: "Central",
      subdivision: "Halasoor Gate",
      phone: "080 22942581",
      email: "piwgarden@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "S.J. Park",
      division: "Central",
      subdivision: "Halasoor Gate",
      phone: "080 22942079",
      email: "sjparkbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Sadashivanagar",
      division: "Central",
      subdivision: "Sheshadripuram",
      phone: "080 22942085",
      email: "ssnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Sheshadripuram",
      division: "Central",
      subdivision: "Sheshadripuram",
      phone: "080 22942586",
      email: "sspurambcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "High Ground",
      division: "Central",
      subdivision: "Sheshadripuram",
      phone: "080 22942083",
      email: "hgroundbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Vyalikaval",
      division: "Central",
      subdivision: "Sheshadripuram",
      phone: "080 22942084",
      email: "vkavalbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Banasawadi",
      division: "East",
      subdivision: "Banasawadi",
      phone: "080 22942552",
      email: "bwadibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Bharathinagar",
      division: "East",
      subdivision: "Pulakeshinagar",
      phone: "080 22942547",
      email: "bnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Byappanahalli",
      division: "East",
      subdivision: "Halasoor",
      phone: "080 22942545",
      email: "bpnhallibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Commercial Street",
      division: "East",
      subdivision: "Pulakeshinagar",
      phone: "080 22942549",
      email: "commercialbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "D.J Halli",
      division: "East",
      subdivision: "Banasawadi",
      phone: "080 22942550",
      email: "djhallibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Halasoor",
      division: "East",
      subdivision: "Halasoor",
      phone: "080 22942540",
      email: "halasoorbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Hennur",
      division: "East",
      subdivision: "Banasawadi",
      phone: "080 22942557",
      email: "hennurbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Indiranagar",
      division: "East",
      subdivision: "Halasoor",
      phone: "080 22942541",
      email: "inagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "J .B. Nagar",
      division: "East",
      subdivision: "Halasoor",
      phone: "080 22942543",
      email: "jbnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "K.G. Halli",
      division: "East",
      subdivision: "Banasawadi",
      phone: "080 22942556",
      email: "kghallibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Pulakeshinagar",
      division: "East",
      subdivision: "Pulakeshinagar",
      phone: "080 22942548",
      email: "ftownbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Rama Murthy Nagar",
      division: "East",
      subdivision: "Banasawadi",
      phone: "080 22942554",
      email: "rmnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Shivaji Nagar",
      division: "East",
      subdivision: "Pulakeshinagar",
      phone: "080 22942597",
      email: "snagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Women PS",
      division: "East",
      subdivision: "Pulakeshinagar",
      phone: "080 22942081",
      email: "hgatewbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Bagalgunte",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942258",
      email: "",
      type: "law_order",
    },
    {
      name: "Gangammanagudi",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942530",
      email: "gggudibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Hebbal",
      division: "North",
      subdivision: "J.C. Nagar",
      phone: "080 22942535",
      email: "hebbalbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "J.C. Nagar",
      division: "North",
      subdivision: "J.C. Nagar",
      phone: "080 22942534",
      email: "jcnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Jalahalli",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942527",
      email: "jhallibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Mahalaxmi Layout",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942523",
      email: "mlayoutbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Malleshwarm",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942519",
      email: "mvmbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Nandini Layout",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942539",
      email: "nlayoutbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Peenya",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942532",
      email: "peenyabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "R.M.C. Yard",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942531",
      email: "rmcyardbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "R.T. Nagar",
      division: "North",
      subdivision: "J.C. Nagar",
      phone: "080 22942538",
      email: "rtnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Rajajinagar",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942522",
      email: "rnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Rajgopal Nagar",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942525",
      email: "rgnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Sanjaynagar",
      division: "North",
      subdivision: "J.C. Nagar",
      phone: "080 22942533",
      email: "sanjaynagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Soladevanahalli",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942529",
      email: "sdhallibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Srirampuram",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942520",
      email: "srpurambcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Subramanyanagar",
      division: "North",
      subdivision: "Malleshwarm",
      phone: "080 22942524",
      email: "sbnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Yeshwanthapura",
      division: "North",
      subdivision: "Yeshwanthapura",
      phone: "080 22942526",
      email: "yspurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Amrutha Halli",
      division: "North East",
      subdivision: "Sampigehalli",
      phone: "080 22943644",
      email: "amruthahallipsbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Bhagalur",
      division: "North East",
      subdivision: "Sampigehalli",
      phone: "080 28463100",
      email: "bhagalurpsbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Chikkajala",
      division: "North East",
      subdivision: "Devanahalli",
      phone: "080 28467200",
      email: "chikkajalabng@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Devanahalli",
      division: "North East",
      subdivision: "Devanahalli",
      phone: "080 27680333",
      email: "devanahallipsbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kempegowda International Airport",
      division: "North East",
      subdivision: "Devanahalli",
      phone: "080 22001102",
      email: "biapsbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kodigehalli",
      division: "North East",
      subdivision: "Yalahanka",
      phone: "080 22943703",
      email: "kodigehallibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kothanuru",
      division: "North East",
      subdivision: "Sampigehalli",
      phone: "080 22943694",
      email: "kottanurbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Sampigehalli",
      division: "North East",
      subdivision: "Sampigehalli",
      phone: "080 22943692",
      email: "sampigehallipsbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Vidyaranyapura",
      division: "North East",
      subdivision: "Yalahanka",
      phone: "080 22942528",
      email: "vrpurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Yalahanka PS",
      division: "North East",
      subdivision: "Yalahanka",
      phone: "080 22942536",
      email: "ylankabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Yelahanka New Town",
      division: "North East",
      subdivision: "Yalahanka",
      phone: "080 22942537",
      email: "ylkntbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Banashankari",
      division: "South",
      subdivision: "Jayanagar",
      phone: "080 22942564",
      email: "bskbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Basavanagudi",
      division: "South",
      subdivision: "Jayanagar",
      phone: "080 22942561",
      email: "bgudibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Basavanagudi women PS",
      division: "South",
      subdivision: "Jayanagar",
      phone: "080 22943250",
      email: "bgudiwbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "C.K.Achchukattu",
      division: "South",
      subdivision: "V.V.Puram",
      phone: "080 22942380",
      email: "ckachukattubcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Girinagar",
      division: "South",
      subdivision: "V.V.Puram",
      phone: "080 22942577",
      email: "gnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Hanumanthanagar",
      division: "South",
      subdivision: "V.V.Puram",
      phone: "080 22942576",
      email: "hnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "J.P. Nagar",
      division: "South",
      subdivision: "Jayanagar",
      phone: "080 22942563",
      email: "jpnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Jayanagar",
      division: "South",
      subdivision: "Jayanagar",
      phone: "080 22942562",
      email: "jnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "K .G. Nagar",
      division: "South",
      subdivision: "V.V.Puram",
      phone: "080 22942578",
      email: "kgnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Konanakunte",
      division: "South",
      subdivision: "Subramanyapura",
      phone: "080 22942560",
      email: "",
      type: "law_order",
    },
    {
      name: "Kumarswamy layout",
      division: "South",
      subdivision: "Subramanyapura",
      phone: "080 22942567",
      email: "kslayoutbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "PuttenaHalli",
      division: "South",
      subdivision: "Subramanyapura",
      phone: "080 22942566",
      email: "",
      type: "law_order",
    },
    {
      name: "Shankarapurm",
      division: "South",
      subdivision: "V.V.Puram",
      phone: "080 22942528",
      email: "skpurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Siddapura",
      division: "South",
      subdivision: "Jayanagar",
      phone: "080 22942572",
      email: "spurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Subramanyapura",
      division: "South",
      subdivision: "Subramanyapura",
      phone: "080 22942565",
      email: "sbpurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "TalaghattaPura",
      division: "South",
      subdivision: "Subramanyapura",
      phone: "080 22942359",
      email: "",
      type: "law_order",
    },
    {
      name: "V.V.Puram",
      division: "South",
      subdivision: "V.V.Puram",
      phone: "080 22942574",
      email: "",
      type: "law_order",
    },
    {
      name: "Adugodi",
      division: "South East",
      subdivision: "Madivala",
      phone: "080 22942573",
      email: "adugodibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Bande Palya",
      division: "South East",
      subdivision: "Electronic City",
      phone: "080 22942236",
      email: "",
      type: "law_order",
    },
    {
      name: "Beguru",
      division: "South East",
      subdivision: "Electronic City",
      phone: "080 22942551",
      email: "",
      type: "law_order",
    },
    {
      name: "BommanaHalli",
      division: "South East",
      subdivision: "Mico Layout",
      phone: "080 22942269",
      email: "",
      type: "law_order",
    },
    {
      name: "Electronic City",
      division: "South East",
      subdivision: "Electronic City",
      phone: "080 22943469",
      email: "electroniccitybcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "H.S.R. Layout",
      division: "South East",
      subdivision: "Madivala",
      phone: "080 22943474",
      email: "hsrlayoutbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Hulimavu",
      division: "South East",
      subdivision: "Electronic City",
      phone: "080 22943470",
      email: "",
      type: "law_order",
    },
    {
      name: "Koramangala",
      division: "South East",
      subdivision: "Madivala",
      phone: "080 22943470",
      email: "kmangalabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Madivala",
      division: "South East",
      subdivision: "Madivala",
      phone: "080 22942568",
      email: "madivalabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Mico Layout",
      division: "South East",
      subdivision: "Mico Layout",
      phone: "080 22942569",
      email: "micobcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Parappana Agrahara",
      division: "South East",
      subdivision: "Electronic City",
      phone: "080 22943468",
      email: "pagraharabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Suddaguntepalya",
      division: "South East",
      subdivision: "Mico Layout",
      phone: "080 22942762",
      email: "",
      type: "law_order",
    },
    {
      name: "Thilaknagar",
      division: "South East",
      subdivision: "Mico Layout",
      phone: "080 22942571",
      email: "tlknagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Annapoorneshwari Nagar",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 23482644",
      email: "",
      type: "law_order",
    },
    {
      name: "Basaveshwara Nagar",
      division: "West",
      subdivision: "Vijayanagar",
      phone: "080 22942516",
      email: "bwnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "ByatarayanaPura",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 22942507",
      email: "bypurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Chamarajapet",
      division: "West",
      subdivision: "Chickpet",
      phone: "080 22942575",
      email: "cmpetbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Chandra Layout",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 22942512",
      email: "clayoutbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "City Market",
      division: "West",
      subdivision: "Chickpet",
      phone: "080 22942502",
      email: "marketbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "CottenPet",
      division: "West",
      subdivision: "Chickpet",
      phone: "080 22942508",
      email: "cotpetbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Jagajeevanram Nagar",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 22942509",
      email: "jjnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Jnanabharathi",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 22942513",
      email: "jbharathibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kalasipalya",
      division: "West",
      subdivision: "Chickpet",
      phone: "080 22942504",
      email: "klpalyabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kamakshipalya",
      division: "West",
      subdivision: "Vijayanagar",
      phone: "080 22942517",
      email: "kmpalyabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kempapura Agrahara",
      division: "West",
      subdivision: "Vijayanagar",
      phone: "080 22942518",
      email: "kpagaraharabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kengeri",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 22942510",
      email: "kengeribcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Magadi Road",
      division: "West",
      subdivision: "Vijayanagar",
      phone: "080 22942515",
      email: "mroadbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Rajarajeswarinagar",
      division: "West",
      subdivision: "Kengeri Gate",
      phone: "080 22942559",
      email: "rrnagar@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Upparpet",
      division: "West",
      subdivision: "Chickpet",
      phone: "080 22942503",
      email: "upetbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Vijayanagar",
      division: "West",
      subdivision: "Vijayanagar",
      phone: "080 22942514",
      email: "vjnagarbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Bellanduru",
      division: "Whitefield",
      subdivision: "Marathahalli",
      phone: "080 25747771",
      email: "",
      type: "law_order",
    },
    {
      name: "H.A.L.",
      division: "Whitefield",
      subdivision: "Marathahalli",
      phone: "080 22942542",
      email: "halbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "K.R. Puram",
      division: "Whitefield",
      subdivision: "Whitefield",
      phone: "080 22942553",
      email: "krpurambcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Kadugodi",
      division: "Whitefield",
      subdivision: "Whitefield",
      phone: "080 22943471",
      email: "kadugodibcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Mahadevapura",
      division: "Whitefield",
      subdivision: "Whitefield",
      phone: "080 22942546",
      email: "mdpurabcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Marathahalli",
      division: "Whitefield",
      subdivision: "Marathahalli",
      phone: "080 25639999",
      email: "",
      type: "law_order",
    },
    {
      name: "Varthur",
      division: "Whitefield",
      subdivision: "Marathahalli",
      phone: "080 28539196",
      email: "varthurbcp@ksp.gov.in",
      type: "law_order",
    },
    {
      name: "Whitefield",
      division: "Whitefield",
      subdivision: "Whitefield",
      phone: "080 22943472",
      email: "whitefieldbcp@ksp.gov.in",
      type: "law_order",
    },
  ],
  traffic: [
    {
      name: "IGP & Additional Commissioner of Police (Traffic)",
      division: "Bengaluru City",
      subdivision: "",
      phone: "080 22862222, 080 22942276",
      mobile: "",
      email: "addlcptrafficbcp@gmail.com",
      type: "traffic",
    },
    {
      name: "Deputy Commissioner of Police (Traffic)",
      division: "East",
      subdivision: "",
      phone: "080 22942346 , 080 22860787",
      mobile: "9480801801",
      email: "dcptrafficeast@gmail.com",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "East",
      subdivision: "Central",
      phone: "080 22942096",
      mobile: "9480801807",
      email: "",
      type: "traffic",
    },
    {
      name: "Cubbon Park Police Station",
      division: "East",
      subdivision: "Central",
      phone: "080 22942675 , 080 22942912",
      mobile: "9480801828",
      email: "cparktrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Ulsoorgate Police Station",
      division: "East",
      subdivision: "Central",
      phone: "080 22942660 , 080 22943124",
      mobile: "9480801829",
      email: "hgatetrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "High Grounds Police Station",
      division: "East",
      subdivision: "Central",
      phone: "080 22942916 , 080 22942671",
      mobile: "9480801827",
      email: "hgroundtrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Sadashivanagar Police Station",
      division: "East",
      subdivision: "Central",
      phone: "080 22942915 , 080 22942804",
      mobile: "9480801830",
      email: "ssnagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Ashoknagar Police Station",
      division: "East",
      subdivision: "Central",
      phone: "080 22943122 , 080 22943123",
      mobile: "9480801823",
      email: "anagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Wilson Garden Police Station",
      division: "East",
      subdivision: "Central",
      phone: "080 22943120",
      mobile: "9480801826",
      email: "wgardentrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "East",
      subdivision: "East",
      phone: "080 22942098",
      mobile: "9480801806",
      email: "",
      type: "traffic",
    },
    {
      name: "Halasuru Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942659 , 080 22942751",
      mobile: "9480801815",
      email: "halasoortrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Indiranagara Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942658 , 080 22942919",
      mobile: "9480801816",
      email: "inagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "K.R.Puram Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942812 , 080 22942927",
      mobile: "9480801818",
      email: "krpuramtrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Shivajinagar Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942920 , 080 22942921",
      mobile: "9480801821",
      email: "shivajinagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Pulikeshi Nagara Traffic Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942925 , 080 22942924",
      mobile: "9480801820",
      email: "ftowntrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Banasawadi Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942217 , 080 22942280",
      mobile: "9480801819",
      email: "bwaditrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "K.G halli Police Station",
      division: "East",
      subdivision: "East",
      phone: "080 22942969",
      mobile: "8123924993",
      email: "kghallitrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "East",
      subdivision: "South East",
      phone: "080 22942115",
      mobile: "9480801805",
      email: "",
      type: "traffic",
    },
    {
      name: "Adugodi Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22943125 , 080 22943119",
      mobile: "9480801822",
      email: "adugoditrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Airport Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22942678 , 080 22943115",
      mobile: "9480801817",
      email: "airporttrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Madivala Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22943116 , 080 22943117",
      mobile: "9480801824",
      email: "madivalatrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Mico Layout Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22943118",
      mobile: "9480801825",
      email: "micolyttrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Electronic City Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22943718",
      mobile: "9480801832",
      email: "electroniccitytrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Whitefield Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22943706",
      mobile: "9480801831",
      email: "whitefieldtrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Hulimavu Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 22942884",
      mobile: "9980826817",
      email: "hulimavutrfeastbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "HSR Layout Traffic Police Station",
      division: "East",
      subdivision: "South East",
      phone: "080 25747574",
      mobile: "9900992998",
      email: "hsrltrafficbcp@gmail.com",
      type: "traffic",
    },
    {
      name: "Deputy Commissioner of Police (Traffic)",
      division: "West",
      subdivision: "",
      phone: "080 22942318 , 080 22862771",
      mobile: "9480801901",
      email: "dcptrafficwest@gmail.com",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "West",
      subdivision: "West",
      phone: "080 22942094",
      mobile: "9480801905",
      email: "",
      type: "traffic",
    },
    {
      name: "Chickpet Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22942664",
      mobile: "9480801916",
      email: "chickpettrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Upparpet Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22942665 , 080 22942910",
      mobile: "9480801915",
      email: "upettrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "City Market Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22942808",
      mobile: "9480801917",
      email: "citymarkettrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Magadi Road Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22942672 , 22943010",
      mobile: "9480801918",
      email: "mroadtrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Vijayanagar Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22942809",
      mobile: "9480801920",
      email: "vjnagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Byatarayanapura Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22942657 , 22943011",
      mobile: "9480801919",
      email: "bypuratrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Kamakshipalya Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22943009",
      mobile: "9480801921",
      email: "kmpalyatrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Kengeri Police Station",
      division: "West",
      subdivision: "West",
      phone: "080 22943013",
      mobile: "",
      email: "kengeritrfbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "West",
      subdivision: "North",
      phone: "080 22942092",
      mobile: "9480801907",
      email: "",
      type: "traffic",
    },
    {
      name: "Malleshwaram Police Station",
      division: "West",
      subdivision: "North",
      phone: "080 22942810 , 080 22943014",
      mobile: "9480801922",
      email: "mvmtrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Rajajinagara Police Station",
      division: "West",
      subdivision: "North",
      phone: "080 22942807 , 080 22943016",
      mobile: "9480801924",
      email: "rnagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Yeshwanthapura Police Station",
      division: "West",
      subdivision: "North",
      phone: "080 22942661",
      mobile: "9480801925",
      email: "yspuratrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Peenya Police Station",
      division: "West",
      subdivision: "North",
      phone: "080 22942674 , 080 22943020",
      mobile: "9480801923",
      email: "peenyatrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Jalahalli Police Station",
      division: "West",
      subdivision: "North",
      phone: "080 22943020",
      mobile: "9880332116",
      email: "jalahallitrfbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "West",
      subdivision: "South",
      phone: "080 22942090",
      mobile: "9480801906",
      email: "",
      type: "traffic",
    },
    {
      name: "V.V  Puram Police Station",
      division: "West",
      subdivision: "South",
      phone: "080 22942670 , 080 22943029",
      mobile: "9480801926",
      email: "cmpettrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Jayanagara Police Station",
      division: "West",
      subdivision: "South",
      phone: "080 22942669 , 080 22943105",
      mobile: "9480801927",
      email: "jnagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Basavanagudi Police Station",
      division: "West",
      subdivision: "South",
      phone: "080 22942668 , 080 22943102",
      mobile: "9480801928",
      email: "bguditrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Banashankari Police Station",
      division: "West",
      subdivision: "South",
      phone: "080 22942673",
      mobile: "9480801930",
      email: "bsktrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Kumarswamy Layout Police Station",
      division: "West",
      subdivision: "South",
      phone: "080 22943109 , 080 22943110",
      mobile: "9480801929",
      email: "kslyttrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Deputy Commissioner of Police (Traffic)",
      division: "North",
      subdivision: "",
      phone: "080 22942318 , 080 22862771",
      mobile: "9480801901",
      email: "dcptrafficnorth@gmail.com",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police (Traffic)",
      division: "North",
      subdivision: "North East",
      phone: "",
      mobile: "9480801073",
      email: "",
      type: "traffic",
    },
    {
      name: "R.T.Nagar Police Station",
      division: "West",
      subdivision: "North East",
      phone: "080 22942813 , 080 22943027",
      mobile: "9480801932",
      email: "rtnagartrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Chikkajala Police Station",
      division: "North",
      subdivision: "North East",
      phone: "080 28467559",
      mobile: "9480801934",
      email: "chikkajalatrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Devanahalli Police Station",
      division: "North",
      subdivision: "North East",
      phone: "080 27681100",
      mobile: "9480801974",
      email: "bialtrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Hebbal Police Station",
      division: "North",
      subdivision: "North East",
      phone: "080 22943023 , 080 22942663",
      mobile: "9480801931",
      email: "hebbaltrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Yellahanka Police Station",
      division: "North",
      subdivision: "North East",
      phone: "080 22943025 , 080 22943024",
      mobile: "9480801933",
      email: "ylktrafficbcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Assistant Commissioner of Police Traffic (Planning)",
      division: "Traffic Admistration Division",
      subdivision: "",
      phone: "080 22942113",
      mobile: "9480801809",
      email: "abletrafficplanningb@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Asst.Commissioner of Police Traffic Training Institute (TTI)",
      division: "Traffic Admistration Division",
      subdivision: "",
      phone: "080 22942117",
      mobile: "9480801808",
      email: "ablettibcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Police Inspector Traffic Training Institute (TTI)",
      division: "Traffic Admistration Division",
      subdivision: "",
      phone: "080 22942117",
      mobile: "",
      email: "pittibcp@ksp.gov.in",
      type: "traffic",
    },
    {
      name: "Police Inspector Traffic Administration",
      division: "Traffic Admistration Division",
      subdivision: "",
      phone: "080 22943030",
      mobile: "",
      email: "",
      type: "traffic",
    },
  ],
  seniors: [
    {
      designation: "Commissioner of Police, Bengaluru City",
      office: "080 22260222 , 080 22942215",
      mobile: "9480801001",
      cug: "1201",
      type: "senior",
    },
    {
      designation: "Addl.C.P, West",
      office: "080 22200902 , 080 22942259",
      mobile: "9480801002",
      cug: "",
      type: "senior",
    },
    {
      designation: "Addl.C.P. Traffic",
      office: "080 22862222 , 080 22942276",
      mobile: "9480801006",
      cug: "1205",
      type: "senior",
    },
    {
      designation: "Addl.C.P, East",
      office: "080 22200904 , 080 22942267",
      mobile: "9480801010",
      cug: "1206",
      type: "senior",
    },
    {
      designation: "Addl.C.P. Admin",
      office: "080 22268374 , 080 22943359",
      mobile: "9480801003",
      cug: "1202",
      type: "senior",
    },
    {
      designation: "Jt.C.P Crime",
      office: "080 22262875 , 080 22942372",
      mobile: "9480801011",
      cug: "1232",
      type: "senior",
    },
    {
      designation: "Jt.C.P INT",
      office: "080 22200924 , 080 22942254",
      mobile: "9480801004",
      cug: "1203",
      type: "senior",
    },
    {
      designation: "DCP Central (Law & Order)",
      office: "080 22200907 , 080 22942344",
      mobile: "9480801101",
      cug: "1301",
      type: "senior",
    },
    {
      designation: "DCP East (Law & Order)",
      office: "080 25567085 , 080 22942312",
      mobile: "9480801201",
      cug: "1401",
      type: "senior",
    },
    {
      designation: "DCP West (Law & Order)",
      office: "080 22370195 , 080 22942356",
      mobile: "9480801701",
      cug: "1901",
      type: "senior",
    },
    {
      designation: "DCP North (Law & Order)",
      office: "080 23567714 , 080 22942299",
      mobile: "9480801301",
      cug: "1501",
      type: "senior",
    },
    {
      designation: "DCP South (Law & Order)",
      office: "080 26635199 , 080 22942309",
      mobile: "9480801501",
      cug: "1701",
      type: "senior",
    },
    {
      designation: "DCP South-East (Law & Order)",
      office: "080 25530284 , 080 22943465",
      mobile: "9480801601",
      cug: "1801",
      type: "senior",
    },
    {
      designation: "DCP North-East (Law & Order)",
      office: "080 23632002 , 080 22943676",
      mobile: "9480801064 , 8105375999",
      cug: "1243",
      type: "senior",
    },
    {
      designation: "DCP Whitefield (Law & Order)",
      office: "",
      mobile: "9480801084",
      cug: "",
      type: "senior",
    },
    {
      designation: "DCP Traffic East (Traffic)",
      office: "080 22860787 , 080 22942346",
      mobile: "9480801801",
      cug: "2001",
      type: "senior",
    },
    {
      designation: "DCP Traffic West (Traffic)",
      office: "080 23362771 , 080 22942318 , 22943034",
      mobile: "9480801901",
      cug: "2002",
      type: "senior",
    },
    {
      designation: "DCP Traffic North (Traffic)",
      office: "",
      mobile: "94808 01133",
      cug: "",
      type: "senior",
    },
    {
      designation: "DCP Admin",
      office: "080 22200918 , 080 22942358",
      mobile: "9480801015",
      cug: "1207",
      type: "senior",
    },
    {
      designation: "DCP Crime",
      office: "080 22200912 , 080 22942366",
      mobile: "9480801016",
      cug: "1208",
      type: "senior",
    },
    {
      designation: "DCP Command Centre",
      office: "080 22202593 , 080 22943177",
      mobile: "9480801092",
      cug: "4315",
      type: "senior",
    },
    {
      designation: "DCP Control Room",
      office: "080 22200914 , 080 22942338",
      mobile: "9480800905",
      cug: "1114",
      type: "senior",
    },
    {
      designation: "DCP Intelligence",
      office: "080 22200920 , 080 22942354",
      mobile: "9480801032",
      cug: "",
      type: "senior",
    },
    {
      designation: "DCP VVIP Sec",
      office: "080 22280020 , 080 22942941",
      mobile: "9480801022",
      cug: "1214",
      type: "senior",
    },
    {
      designation: "DCP V.S.Security",
      office: "080 22353129 , 080 22033968 , 080 22943554",
      mobile: "9480801109",
      cug: "1250",
      type: "senior",
    },
    {
      designation: "DCP Crime – 2",
      office: "080 22259590 , 080 22942374",
      mobile: "94808 01021",
      cug: "1213",
      type: "senior",
    },
    {
      designation: "DCP CAR (HQ)",
      office: "080 26701406 , 080 22942415",
      mobile: "9480801017",
      cug: "1209",
      type: "senior",
    },
    {
      designation: "DCP CAR (South)",
      office: "080 25710856 , 080 22942370",
      mobile: "9480801019",
      cug: "1211",
      type: "senior",
    },
    {
      designation: "DCP CAR (North)",
      office: "080 28465406 , 080 22942368",
      mobile: "9480801018",
      cug: "1210",
      type: "senior",
    },
  ],
};
